import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import './navStyle.css';
import Navbar from '@/components/Navbar/navbar';
import { SettingsProvider } from '@/hooks/useSettings'; 

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const dancingScript = localFont({
  src: [
    {
      path: '../public/fonts/static/DancingScript-Bold.ttf',
      weight: '700',
    },
    {
      path: '../public/fonts/static/DancingScript-SemiBold.ttf',
      weight: '600',
    },
    {
      path: '../public/fonts/static/DancingScript-Regular.ttf',
      weight: '400',
    },
    {
      path: '../public/fonts/static/DancingScript-Medium.ttf',
      weight: '500',
    },
  ],
  variable: '--font-DancingScript',
});

const latoFont = Lato({
  weight: ['300', '400', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`min-h-screen antialiased ${latoFont.className} ${dancingScript.variable}`}
    >
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <body suppressHydrationWarning={true}>
        <SettingsProvider> 
          <main
            id="mainPage"
            className="fixed w-screen h-svh p-0 m-0 items-center justify-center overflow-hidden text-lightMainColor dark:text-darkMainColor bg-lightMainBG dark:bg-darkMainBG"
          >
            <Navbar path={''} locale={'EN'}>
              {children}
            </Navbar>
          </main>
        </SettingsProvider>
      </body>
    </html>
  );
}
